Add pytest fixture support
belgeu/misc pull request #4
Opened 2017-02-16 09:48 UTC by belgeu

Currently test has no setup/teardown workflow.

Add pytest's builtin fixture support in order to provide ability to
execute [setup] and [teardown] steps before and after each test case run.

2017-02-16 11:57 UTC, extsoft commented on python/webdriver_test.py
> +    request.b = webdriver.Firefox()
Don't add driver to requests.  Use 
```
driver = webdriver.Firefox()
.....
return driver
```

2017-02-16 11:59 UTC, extsoft requested changes

2017-02-16 11:59 UTC, extsoft commented on python/webdriver_test.py
> +def setup(request):
Pls rename fixture (`browser` etc.)

2017-02-16 11:59 UTC, extsoft commented on python/webdriver_test.py
> +    request.b = webdriver.Firefox()
Don't add driver to requests.  Use 
```
driver = webdriver.Firefox()
.....
return driver
```

2017-02-16 13:48 UTC, belgeu commented on python/webdriver_test.py
> +def setup(request):
Changed fixture name to 'browser'

2017-02-16 13:49 UTC, belgeu commented on python/webdriver_test.py
> +    request.b = webdriver.Firefox()
Modified fixture to return webdriver object separately from request.

2017-02-17 10:32 UTC, extsoft requested changes

2017-02-17 10:32 UTC, extsoft commented on python/webdriver_test.py
> +    b = browser
Why do you create this `b`?

2017-02-17 11:30 UTC, belgeu commented on python/webdriver_test.py
> +    b = browser
The idea is to keep code a bit shorter, but i see your point. Switched webdriver naming to "browser", it certainly improves code readability. Thanks.

2017-02-17 13:01 UTC, extsoft approved these changes

2017-02-17 13:02 UTC, merged