Structurize project according to the style guide
belgeu/misc pull request #5
Opened 2017-02-20 14:51 UTC by belgeu

Since structuring of a project makes it a lot easier to navigate through project files, current project files were re-arranged to keep them in line with the following style guide - http://docs.python-guide.org/en/latest/writing/structure/ .

2017-02-21 10:03 UTC, extsoft requested changes

2017-02-21 10:03 UTC, extsoft commented on python/pip_packages.txt
> +###### PIP packages ######
File name has to be "requirements.txt".

2017-02-21 10:03 UTC, extsoft commented on python/tests/webdriver_test.py
> +import pytest
Must be in `python/test_sample/`. In this package we have only unit tests.
The same about `python/tests/unit_test.py` file.

2017-02-21 12:16 UTC, belgeu commented on python/pip_packages.txt
> +###### PIP packages ######
Re-named to "requirements.txt".

2017-02-21 12:17 UTC, belgeu commented on python/tests/webdriver_test.py
> +import pytest
Re-placed to `python/test_sample/` directory.

2017-02-28 12:58 UTC, extsoft approved these changes

2017-02-28 13:31 UTC, merged